name: receiptviewerweb
description: Consent Receipt web viewer

version: 1.0.0+10000

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  receiptviewer:
    path: ../receipt_viewer
  url_launcher: ^5.4.5
  intl: ^0.16.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9
  lint: ^1.1.1
  build_runner: ^1.9.0
  freezed: ^0.10.7

flutter:
  uses-material-design: true
  assets:
    - assets/by_x0A.png
    - assets/CutiveMono-Regular.ttf
  fonts:
    - family: CutiveMono
      fonts:
        - asset: assets/CutiveMono-Regular.ttf

flutter_intl:
  enabled: true