name: content_wallet
description: A wallet for consent receipts

version: 1.2.0+10200

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.2
  hive: ^1.4.1+1
  intl: ^0.16.1
  package_info: ^0.4.0+16
  url_launcher: ^5.4.2
  freezed_annotation: ^0.7.1
  get: ^1.14.1-dev
  flutter_bloc: ^3.2.0
  json_serializable: ^3.3.0
  catcher: ^0.3.4
  flutter_document_picker: ^4.0.0
  wc_flutter_share: 0.2.0
  receiptviewer:
    path: ../receipt_viewer

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9
  lint: ^1.1.1
  build_runner: ^1.8.1
  freezed: ^0.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/by_x0A.png
    - assets/CutiveMono-Regular.ttf
  fonts:
    - family: CutiveMono
      fonts:
        - asset: assets/CutiveMono-Regular.ttf
