name: receiptviewer
description: >
  Consent receipt viewer components
version: 1.0.0
author:
  - Javier Freire <javier.freire@x0.io>
homepage: https://github.com/x0aio/consentwallet

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  freezed_annotation: ^0.7.1
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9
  lint: ^1.1.1
  build_runner: ^1.8.1
  freezed: ^0.10.5